settings:
  teleport-on-join: true

warps:
  farmwelt:
    world: farmwelt
    x: 0
    y: 120
    z: 0
    yaw: 0
    pitch: 0

  nether:
    world: Nether
    x: 0
    y: 60
    z: 0
    yaw: 0
    pitch: 0

spawn-protection:
  enabled: true
  worlds:
    - farmwelt
    - Nether

  area:
    radius-xz: 12
    min-y: -64
    max-y: 319

  block:
    break: true
    place: true

  inventory:
    open: true

  combat:
    pvp: true
    mob-damage: true

  damage:
    fall: true
    fire: true
    lava: true
    explosion: true
